etudiantmaster_index:
    path:     /
    defaults: { _controller: "ReregistrationBundle:EtudiantMaster:index" }
    methods:  GET

etudiantmaster_show:
    path:     /{id}/show
    defaults: { _controller: "ReregistrationBundle:EtudiantMaster:show" }
    methods:  GET

etudiantmaster_new:
    path:     /new
    defaults: { _controller: "ReregistrationBundle:EtudiantMaster:new" }
    methods:  [GET, POST]

etudiantmaster_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReregistrationBundle:EtudiantMaster:edit" }
    methods:  [GET, POST]

etudiantmaster_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReregistrationBundle:EtudiantMaster:delete" }
    methods:  DELETE
