etudiant_show:
    path:     /{id}/show
    defaults: { _controller: "ReregistrationBundle:Etudiant:show" }
    methods:  GET

etudiant_new:
    path:     /
    defaults: { _controller: "ReregistrationBundle:Etudiant:new" }
    methods:  [GET, POST]

etudiant_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReregistrationBundle:Etudiant:edit" }
    methods:  [GET, POST]

etudiant_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReregistrationBundle:Etudiant:delete" }
    methods:  DELETE

etudiant_index:
    path:     /
    defaults: { _controller: "ReregistrationBundle:Etudiant:index" }
    methods:  GET