sonata_admin:
    security:
        information:
            GUEST:    []
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      FL-SAISS
    title_logo: "/bundles/reregistration/assets/images/saiss.jpg"
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display
        sort_admins:          false
        confirm_exit:         true
        use_select2:          true
        use_icheck:           true
        use_bootlint:         false
        use_stickyforms:      true
        form_type:            standard
        dropdown_number_groups_per_colums:  2
        title_mode:          single_text # One of "single_text"; "single_image"; "both"

    templates:
        layout:                     SonataAdminBundle::standard_layout.html.twig
        ajax:                       SonataAdminBundle::ajax_layout.html.twig
        search:                     SonataAdminBundle:Core:search.html.twig
        search_result_block:        SonataAdminBundle:Block:block_search_result.html.twig
        show:                       SonataAdminBundle:CRUD:show.html.twig
        edit:                       SonataAdminBundle:CRUD:edit.html.twig
        list:                       SonataAdminBundle:CRUD:list.html.twig
        action:                     SonataAdminBundle:CRUD:action.html.twig
        select:                     SonataAdminBundle:CRUD:list__select.html.twig
        list_block:                 SonataAdminBundle:Block:block_admin_list.html.twig
        short_object_description:   SonataAdminBundle:Helper:short-object-description.html.twig
        batch:                      SonataAdminBundle:CRUD:list__batch.html.twig
        inner_list_row:             SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:            SonataAdminBundle:CRUD:base_list_field.html.twig
        pager_links:                SonataAdminBundle:Pager:links.html.twig
        pager_results:              SonataAdminBundle:Pager:results.html.twig

    dashboard:
        blocks:
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <div class='panel panel-success'>
                          <div class='panel-heading text-center'>
                            <h3 class='panel-title'>Bienvenue</h3>
                          </div>
                          <div class='panel-body'>
                            La partie da'administaration pour l'inscriptionet reinscription des etudiant
                            de
                            Faculté des lettres et sciences humaines Sais-Fes
                          </div>
                        </div>
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata.admin.group.etudiants, sonata.admin.group.filieres, sonata.admin.group.administration]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata.admin.group.content]

        groups:
            sonata.admin.group.etudiants:
                label:           Etudiants
                label_catalogue: ReregistrationBundle
                icon:            '<i class="fa fa-users"></i>'
                items:
                    - reregistration.admin.etudiant_deug
                    - reregistration.admin.etudiant_licence
                    - reregistration.admin.etudiant_master
                    - reregistration.admin.etudiant_doctorat

            sonata.admin.group.filieres:
                label:           Filières
                label_catalogue: ReregistrationBundle
                icon:            '<i class="fa fa-list"></i>'
                items:
                    - reregistration.admin.filiere_deug
                    - reregistration.admin.filiere_licence
                    - reregistration.admin.filiere_master
                    - reregistration.admin.labo_doctorat

            sonata.admin.group.content:
                label:           Les Contenus
                label_catalogue: ReregistrationBundle
                icon:            '<i class="fa fa-dashboard"></i>'
                items:
                    - reregistration.admin.academie
                    - reregistration.admin.etablessement
                    - reregistration.admin.mention
                    - reregistration.admin.serie_du_bac
                    - reregistration.admin.type_bac
                    - reregistration.admin.type_diplome
                    - reregistration.admin.parcours
                    - reregistration.admin.universite
                    - reregistration.admin.fonction
                    - reregistration.admin.pays
                    - reregistration.admin.ville

            sonata.admin.group.administration:
                label:           Administration
                label_catalogue: ReregistrationBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - geek_dos_user.admin.user
                    - reregistration.admin.configuration
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection