reregistration_etudiant:
    resource: "@ReregistrationBundle/Resources/config/routing/etudiant.yml"
    prefix:   /inscription

reregistration_homepage:
    path:     /
    defaults: { _controller: ReregistrationBundle:Default:index }

reregistration_choix_filiere:
    path:     /choix/filiere
    defaults: { _controller: ReregistrationBundle:ChoixFiliere:index }

reregistration_registration:
    path:     /inscription
    defaults: { _controller: ReregistrationBundle:Inscription:index }

reregistration_registration_deug:
    path:     /inscription/deug
    defaults: { _controller: ReregistrationBundle:Inscription:deug }

reregistration_registration_licence:
    path:     /inscription/licence/{parcours_id}
    defaults: { _controller: ReregistrationBundle:Inscription:licence }

reregistration_registration_master:
    path:     /inscription/master
    defaults: { _controller: ReregistrationBundle:Inscription:master }

reregistration_registration_doctorat:
    path:     /inscription/doctorat
    defaults: { _controller: ReregistrationBundle:Inscription:doctorat }

reregistration_re_registration:
    path:     /re-inscription
    defaults: { _controller: ReregistrationBundle:ReInscription:index }

reregistration_re_registration_edite:
    path:     /re-inscription/edite
    defaults: { _controller: ReregistrationBundle:ReInscription:edit}

reregistration_re_registration_checking:
    path:     /re-inscription/checking
    defaults: { _controller: ReregistrationBundle:ReInscription:checking }
