services:
#    reregistration.example:
#        class: ReregistrationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    reregistration.admin.academie:
        class: ReregistrationBundle\Admin\AcademieAdmin
        arguments: [~, ReregistrationBundle\Entity\Academie, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Academie }

    reregistration.admin.etablessement:
        class: ReregistrationBundle\Admin\EtablessementAdmin
        arguments: [~, ReregistrationBundle\Entity\Etablessement, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Etablessement }

    reregistration.admin.fonction:
        class: ReregistrationBundle\Admin\FonctionAdmin
        arguments: [~, ReregistrationBundle\Entity\Fonction, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Fonction }

    reregistration.admin.mention:
        class: ReregistrationBundle\Admin\MentionAdmin
        arguments: [~, ReregistrationBundle\Entity\Mention, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mention }

    reregistration.admin.parcours:
        class: ReregistrationBundle\Admin\ParcoursAdmin
        arguments: [~, ReregistrationBundle\Entity\Parcours, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Parcours }

    reregistration.admin.pays:
        class: ReregistrationBundle\Admin\PaysAdmin
        arguments: [~, ReregistrationBundle\Entity\Pays, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pays }

    reregistration.admin.serie_du_bac:
        class: ReregistrationBundle\Admin\SerieDuBacAdmin
        arguments: [~, ReregistrationBundle\Entity\SerieDuBac, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SerieDuBac }

    reregistration.admin.type_bac:
        class: ReregistrationBundle\Admin\TypeBacAdmin
        arguments: [~, ReregistrationBundle\Entity\TypeBac, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TypeBac }

    reregistration.admin.type_diplome:
        class: ReregistrationBundle\Admin\TypeDiplomeAdmin
        arguments: [~, ReregistrationBundle\Entity\TypeDiplome, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TypeDiplome }

    reregistration.admin.universite:
        class: ReregistrationBundle\Admin\UniversiteAdmin
        arguments: [~, ReregistrationBundle\Entity\Universite, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Universite }

    reregistration.admin.ville:
        class: ReregistrationBundle\Admin\VilleAdmin
        arguments: [~, ReregistrationBundle\Entity\Ville, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ville }

    reregistration.admin.user:
        class: ReregistrationBundle\Admin\UserAdmin
        arguments: [~, ReregistrationBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }

    reregistration.admin.etat_actuel:
        class: ReregistrationBundle\Admin\EtatActuelAdmin
        arguments: [~, ReregistrationBundle\Entity\EtatActuel, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtatActuel }

    reregistration.admin.province:
        class: ReregistrationBundle\Admin\ProvinceAdmin
        arguments: [~, ReregistrationBundle\Entity\Province, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Province }

    reregistration.admin.configuration:
        class: ReregistrationBundle\Admin\ConfigurationAdmin
        arguments: [~, ReregistrationBundle\Entity\Configuration, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Configuration }

    reregistration.admin.etudiant_deug:
        class: ReregistrationBundle\Admin\EtudiantDeugAdmin
        arguments: [~, ReregistrationBundle\Entity\EtudiantDeug, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantDeug }

    reregistration.admin.etudiant_doctorat:
        class: ReregistrationBundle\Admin\EtudiantDoctoratAdmin
        arguments: [~, ReregistrationBundle\Entity\EtudiantDoctorat, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantDoctorat }

    reregistration.admin.etudiant_licence:
        class: ReregistrationBundle\Admin\EtudiantLicenceAdmin
        arguments: [~, ReregistrationBundle\Entity\EtudiantLicence, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantLicence }

    reregistration.admin.etudiant_master:
        class: ReregistrationBundle\Admin\EtudiantMasterAdmin
        arguments: [~, ReregistrationBundle\Entity\EtudiantMaster, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantMaster }

    reregistration.admin.filiere_deug:
        class: ReregistrationBundle\Admin\FiliereDeugAdmin
        arguments: [~, ReregistrationBundle\Entity\FiliereDeug, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FiliereDeug }

    reregistration.admin.filiere_licence:
        class: ReregistrationBundle\Admin\FiliereLicenceAdmin
        arguments: [~, ReregistrationBundle\Entity\FiliereLicence, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FiliereLicence }

    reregistration.admin.filiere_master:
        class: ReregistrationBundle\Admin\FiliereMasterAdmin
        arguments: [~, ReregistrationBundle\Entity\FiliereMaster, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FiliereMaster }

    reregistration.admin.labo_doctorat:
        class: ReregistrationBundle\Admin\LaboDoctoratAdmin
        arguments: [~, ReregistrationBundle\Entity\LaboDoctorat, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: LaboDoctorat }
