services:
    usmba_fl_registration.admin.academie:
        class: Usmba\FLRegistrationBundle\Admin\AcademieAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Academie, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Academie }

    usmba_fl_registration.admin.categorie_socio_professionnelle:
        class: Usmba\FLRegistrationBundle\Admin\CategorieSocioProfessionnelleAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\CategorieSocioProfessionnelle, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CategorieSocioProfessionnelle }

    usmba_fl_registration.admin.etablissement:
        class: Usmba\FLRegistrationBundle\Admin\EtablissementAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Etablissement, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Etablissement }

    usmba_fl_registration.admin.etablissement_bac:
        class: Usmba\FLRegistrationBundle\Admin\EtablissementBacAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\EtablissementBac, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtablissementBac }

    usmba_fl_registration.admin.etudiant:
        class: Usmba\FLRegistrationBundle\Admin\EtudiantAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Etudiant, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Etudiant }

    usmba_fl_registration.admin.etudiant_bac_plus_deux:
        class: Usmba\FLRegistrationBundle\Admin\EtudiantBacPlusDeuxAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\EtudiantBacPlusDeux, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantBacPlusDeux }

    usmba_fl_registration.admin.etudiant_doctorat:
        class: Usmba\FLRegistrationBundle\Admin\EtudiantDoctoratAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\EtudiantDoctorat, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantDoctorat }

    usmba_fl_registration.admin.etudiant_licence:
        class: Usmba\FLRegistrationBundle\Admin\EtudiantLicenceAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\EtudiantLicence, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantLicence }

    usmba_fl_registration.admin.etudiant_master:
        class: Usmba\FLRegistrationBundle\Admin\EtudiantMasterAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\EtudiantMaster, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EtudiantMaster }

    usmba_fl_registration.admin.filiere:
        class: Usmba\FLRegistrationBundle\Admin\FiliereAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Filiere, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Filiere }

    usmba_fl_registration.admin.mention:
        class: Usmba\FLRegistrationBundle\Admin\MentionAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Mention, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mention }

    usmba_fl_registration.admin.parcours:
        class: Usmba\FLRegistrationBundle\Admin\ParcoursAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Parcours, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Parcours }

    usmba_fl_registration.admin.pays:
        class: Usmba\FLRegistrationBundle\Admin\PaysAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Pays, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pays }

    usmba_fl_registration.admin.province:
        class: Usmba\FLRegistrationBundle\Admin\ProvinceAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Province, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Province }

    usmba_fl_registration.admin.serie_du_bac:
        class: Usmba\FLRegistrationBundle\Admin\SerieDuBacAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\SerieDuBac, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SerieDuBac }

    usmba_fl_registration.admin.situation_famille:
        class: Usmba\FLRegistrationBundle\Admin\SituationFamilleAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\SituationFamille, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SituationFamille }

    usmba_fl_registration.admin.specialite:
        class: Usmba\FLRegistrationBundle\Admin\SpecialiteAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Specialite, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Specialite }

    usmba_fl_registration.admin.type_bac:
        class: Usmba\FLRegistrationBundle\Admin\TypeBacAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\TypeBac, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TypeBac }

    usmba_fl_registration.admin.type_diplome:
        class: Usmba\FLRegistrationBundle\Admin\TypeDiplomeAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\TypeDiplome, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TypeDiplome }

    usmba_fl_registration.admin.universite:
        class: Usmba\FLRegistrationBundle\Admin\UniversiteAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Universite, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Universite }

    usmba_fl_registration.admin.ville:
        class: Usmba\FLRegistrationBundle\Admin\VilleAdmin
        arguments: [~, Usmba\FLRegistrationBundle\Entity\Ville, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ville }
