<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * CategorieSocioProfessionnelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieSocioProfessionnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
