<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * EtablissementBacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementBacRepository extends \Doctrine\ORM\EntityRepository
{
}
