<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * EtudiantBacPlusDeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantBacPlusDeuxRepository extends \Doctrine\ORM\EntityRepository
{
}
