<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * EtudiantLicenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantLicenceRepository extends \Doctrine\ORM\EntityRepository
{
}
