<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * EtudiantDoctoratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantDoctoratRepository extends \Doctrine\ORM\EntityRepository
{
}
