<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * SerieDuBacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieDuBacRepository extends \Doctrine\ORM\EntityRepository
{
}
