<?php

namespace Usmba\FLRegistrationBundle\Repository;

/**
 * SituationFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationFamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
