<?php

namespace ReregistrationBundle\Repository;

/**
 * AcademieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademieRepository extends \Doctrine\ORM\EntityRepository
{
}
