<?php

namespace ReregistrationBundle\Repository;

/**
 * EtablessementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablessementRepository extends \Doctrine\ORM\EntityRepository
{
}
