<?php

namespace ReregistrationBundle\Repository;

/**
 * EtatActuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatActuelRepository extends \Doctrine\ORM\EntityRepository
{
}
