<?php

namespace ReregistrationBundle\Repository;

/**
 * EtudiantMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
