<?php

namespace ReregistrationBundle\Repository;

/**
 * FiliereDeugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereDeugRepository extends \Doctrine\ORM\EntityRepository
{
}
