<?php

namespace ReregistrationBundle\Repository;

/**
 * FiliereLicenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereLicenceRepository extends \Doctrine\ORM\EntityRepository
{
}
