<?php

namespace ReregistrationBundle\Repository;

/**
 * FiliereMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
