<?php

namespace ReregistrationBundle\Repository;

/**
 * LaboDoctoratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboDoctoratRepository extends \Doctrine\ORM\EntityRepository
{
}
