<?php

namespace ReregistrationBundle\Repository;

/**
 * TypeBacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBacRepository extends \Doctrine\ORM\EntityRepository
{
}
