<?php

namespace ReregistrationBundle\Repository;

/**
 * TypeDiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDiplomeRepository extends \Doctrine\ORM\EntityRepository
{
}
